version: '3'
services:
  # cache:
  #   image: memcached
  #   ports:
  #     - "11811:11311"
  #   entrypoint:
  #     - memcached
  #     - -m 64
     
  django:
    build:
      context: ./unchained
      dockerfile: Dockerfile
    env_file:
      - communitysecrets/community.env
    command: bash -c "cd unchained/community && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: unchained
    volumes:
      - .:/unchained
    ports:
      - "8000:8000"

# python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000
# uwsgi --http :8000 --module community.wsgi