# Generated by Django 2.0.7 on 2018-09-14 02:20

import community.validators
import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover_image',
            field=models.FileField(blank=True, upload_to=course.models.get_upload_path, validators=[community.validators.validate_image_file_extension]),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.FileField(blank=True, upload_to=course.models.get_upload_path, validators=[community.validators.validate_image_file_extension]),
        ),
    ]
