# Generated by Django 2.0.7 on 2018-09-14 02:32

import community.validators
import course.models
from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20180914_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover_image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=course.models.get_upload_path, validators=[community.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=course.models.get_upload_path, validators=[community.validators.validate_image_file_extension]),
        ),
    ]
