# Generated by Django 2.0.7 on 2018-09-14 02:52

import community.validators
import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20180914_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, upload_to=course.models.get_upload_path, validators=[community.validators.validate_image_file_extension]),
        ),
    ]
