# Generated by Django 2.0.7 on 2018-09-14 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0001_initial'),
        ('course', '0002_remove_course_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='coursefiles')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='course.Course')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='institution.Institution')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
