# Generated by Django 2.0.7 on 2018-09-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20180914_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registration',
            field=models.CharField(default='sample', max_length=100),
            preserve_default=False,
        ),
    ]
