# Generated by Django 2.0.7 on 2018-09-15 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='registration',
            new_name='uid',
        ),
    ]
