# Generated by Django 2.0.7 on 2018-09-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20180915_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
