# Generated by Django 2.1.5 on 2019-02-11 20:17

import community.validators
from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20180915_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.FileField(blank=True, upload_to=student.models.get_upload_path, validators=[community.validators.validate_image_file_extension]),
        ),
    ]
